version: "3.6"

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-tests

  api-tests:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      PYTHON_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: api-tests
      # SANBASE_GQL_HOST: https://api-stage.santiment.net/graphql
      # API_KEY:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    depends_on:
      - postgres
