FROM python:3.7.4-slim as builder

ARG PYTHON_ENV=production
ARG API_KEY

ENV PYTHON_ENV=${PYTHON_ENV}
ENV API_KEY=${API_KEY}

WORKDIR /app

RUN apt update && apt install gcc libpq-dev -y

COPY requirements.txt /app/requirements.txt
COPY dev-requirements.txt /app/dev-requirements.txt

RUN pip3 wheel -r requirements.txt -w /wheels
RUN pip wheel -r dev-requirements.txt -w /wheels

FROM python:3.7.4-slim

WORKDIR /app

COPY --from=builder /wheels /wheels

COPY requirements.txt /app/requirements.txt
COPY dev-requirements.txt /app/dev-requirements.txt

RUN pip3 install -r requirements.txt --find-links /wheels
RUN pip3 install -r dev-requirements.txt --find-links /wheels

COPY . /app

ENV PYTHONPATH /app

WORKDIR /app

CMD ["flask", "run", "--host=0.0.0.0"]